# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Swift Alone
email: dreymonde@me.com
description: > # this means to ignore newlines until "baseurl:"
  A tiny blog about my own Swift thoughts and discoveries. Highly opinionated. Mostly for beginners.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dreymonde.github.io" # the base hostname & protocol for your site
twitter_username: dreymonde
github_username:  dreymonde

# Build settings
markdown: kramdown
